import { AUTH_ENDPOINT } from ".";
import { SP_NAME } from "./spName";

export const API_ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  GET_FRANCHISE_LOGO_AND_NAME: `/execute-sp/auth-all/SpUsers/2`,

  RESET_USER_DEVICE: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_USERS}/3`,
  // IS_ACTIVE_TOGGLE_USER: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_USERS}/4`,

  GET_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/1`,
  UPSERT_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/2`,

  GET_STUDENT_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/1`,
  UPSERT_STUDENT_DETAILS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/2`,
  GET_STUDENT_DETAILS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/3`,
  REGISTER_STUDENT: "/auth/register-student",

  GET_CATEGORY_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/1`,
  UPSERT_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/2`,
  DELETE_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/3`,
  GET_CATEGORY_PARENT_CHILD_BY_ID: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/4`,
  GET_PARENT_CATEGORY_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_CATEGORY}/5`,

  UPSERT_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/1`,
  GET_QUESTION_ANS_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/2`,
  DELETE_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/3`,
  GET_QUESTION_ANS_BY_ID: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/4`,
  GET_FILTERED_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/5`,
  BULK_UPSERT_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/6`,

  GET_TEST_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/1`,
  UPSERT_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/2`,
  DELETE_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/3`,
  GET_TEST_BY_ID: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/4`,
  GET_FULL_TEST_DETAILS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/5`,
  TOGGLE_BOOKMARK: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST}/6`,

  UPSERT_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST_QUESTIONS}/1`,
  GET_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_TEST_QUESTIONS}/2`,

  GET_FRANCHISE_DROP_DOWN: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/SpCommonDropDownList/1`,
  GET_FRANCHISE_TEST_MAPPINGS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/SpCommonDropDownList/2`,
  SAVE_FRANCHISE_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/7`,

  GET_DISPLAY_VIEW_LIST: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/1`,
  GET_DISPLAY_VIEW_LIST_FOR_STUDENT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/7`,
  UPSERT_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/2`,
  DELETE_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/3`,
  GET_DISPLAY_VIEW_CHILDREN: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW}/4`,
  GET_DISPLAY_VIEW_STUDENT_LIST:  `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/5`,
  ASSIGN_DISPLAY_VIEW: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW}/6`,

  // DisplayViewTest — assign tests to display view nodes
  UPSERT_DISPLAY_VIEW_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/1`,
  DELETE_DISPLAY_VIEW_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/2`,
  GET_DISPLAY_VIEW_TESTS: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_DISPLAY_VIEW_TEST}/3`,

  // Practice Attempts — accessible by all authenticated users
  // Backend SP: SpAttempt
  // Payload for START_ATTEMPT:   { test_id: number }
  // Returns:                     { id, student_id, test_id, score, started_at }
  // Payload for SUBMIT_ATTEMPT:  { attempt_id: number, answers: [{ question_id, selected_option_id }] }
  // Returns:                     { attempt_id, score, total_questions, correct_answers }
  START_ATTEMPT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/1`,
  SUBMIT_ATTEMPT: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/2`,
  GET_ATTEMPT_REVIEW: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/3`,
  GET_ATTEMPT_HISTORY: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_ATTEMPT}/4`,
  GET_LEADERBOARD: `/${AUTH_ENDPOINT.ALL}/${SP_NAME.SP_LEADERBOARD}/1`,
};