import { AUTH_ENDPOINT } from ".";
import { SP_NAME } from "./spName";

export const API_ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",

  GET_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/1`,
  UPSERT_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/2`,

  GET_STUDENT_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/1`,
  REGISTER_STUDENT: "/auth/register-student",

  GET_CATEGORY_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/1`,
  UPSERT_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/2`,
  DELETE_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/3`,
  GET_CATEGORY_PARENT_CHILD_BY_ID: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/4`,
  GET_PARENT_CATEGORY_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/5`,

  UPSERT_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/1`,
  GET_QUESTION_ANS_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/2`,
  DELETE_QUESTION_ANS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/3`,
  GET_QUESTION_ANS_BY_ID: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/4`,
  GET_FILTERED_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_QUESTION_ANS}/5`,

  GET_TEST_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/1`,
  UPSERT_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/2`,
  DELETE_TEST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/3`,
  GET_TEST_BY_ID: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST}/4`,

  UPSERT_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST_QUESTIONS}/1`,
  GET_TEST_QUESTIONS: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_TEST_QUESTIONS}/2`,
};