import { AUTH_ENDPOINT } from ".";
import { SP_NAME } from "./spName";

export const API_ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",

  GET_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/1`,
  UPSERT_FRANCHISE_LIST: `/${AUTH_ENDPOINT.ONLY_ADMIN}/${SP_NAME.SP_FRANCHISE}/2`,

  GET_STUDENT_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_STUDENT}/1`,
  REGISTER_STUDENT: "/auth/register-student",

  GET_CATEGORY_LIST: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/1`,
  UPSERT_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/2`,
  DELETE_CATEGORY: `/${AUTH_ENDPOINT.ADMIN_AND_FRANCHISE}/${SP_NAME.SP_CATEGORY}/3`,
};